# Use an official lightweight Node.js image as the base
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy all files from the current directory to the working directory in the container
COPY . .

# Expose port 5500 to the outside world
EXPOSE 5500

# Install a simple HTTP server
RUN npm install -g http-server

# Command to run the HTTP server and serve static files
CMD ["http-server", "-p", "5500"]
